"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](bg:color_bg0)\
$os\
[](bg:color_bg1 fg:color_bg0)\
$directory\
[](fg:color_bg1 bg:color_bg2)\
$git_branch\
$git_status\
[](fg:color_bg2 bg:color_bg3)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$python\
[](fg:color_bg3 bg:color_bg4)\
$time\
[ ](fg:color_bg4)\
\n$character"""

palette = 'tokyo_night_preset'

[palettes.tokyo_night_preset]
color_bg0 = '#a3aed2'
color_bg1 = '#769ff0'
color_bg2 = '#394260'
color_bg3 = '#212736'
color_bg4 = '#1d2230'
color_os = '#090c0c'
color_dir = '#e3e5e5'
color_dev = '#769ff0'
color_time = '#a0a9cb'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_bg0 fg:color_os"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
EndeavourOS = "  "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "

[directory]
style = "fg:color_dir bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol $branch ](fg:color_dev bg:color_bg2)]($style)'

[git_status]
style = "bg:color_bg2"
format = '[[($all_status$ahead_behind )](fg:color_dev bg:color_bg2)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[c]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[cpp]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[rust]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[golang]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[php]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[java]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[python]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol ($version) ](fg:color_dev bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_bg4"
format = '[[  $time ](fg:color_time bg:color_bg4)]($style)'
